"""Generate Solidity wire declarations from the frozen schema, never golden outputs."""

import argparse
import json
import subprocess
from pathlib import Path

from check_abi import schemaAbiField

ROOT = Path(__file__).resolve().parents[1]
SCALARS = {
    "Address": "address",
    "Digest": "bytes32",
    "Signature": "bytes",
    "Uri": "string",
    "Uint64": "uint64",
    "Uint96": "uint96",
    "Uint256": "uint256",
    "Int256": "int256",
}
HEADER = (
    "// SPDX-License-Identifier: MIT\n"
    "// Generated by scripts/generate_contract_types.py; do not edit.\n"
    "pragma solidity 0.8.30;\n\n"
)


def generate():
    definitions = json.loads((ROOT / "specs/schemas/protocol.schema.json").read_text())["$defs"]
    catalog = json.loads((ROOT / "specs/catalog.json").read_text())
    structs = {}

    def solidityType(schema, suggested):
        if "allOf" in schema and "type" not in schema:
            return solidityType(schema["allOf"][0], suggested)
        if "$ref" in schema:
            name = schema["$ref"].split("/")[-1]
            if name in SCALARS:
                return SCALARS[name]
            return solidityType(definitions[name], name)
        if "anyOf" in schema:
            child = schema["anyOf"][0]
            name = child.get("$ref", suggested).split("/")[-1]
            optional = "Optional" + name
            if optional not in structs:
                childType = solidityType(child, name)
                structs[optional] = [("bool", "present"), (childType, "value")]
            return optional
        if schema.get("type") == "object":
            if suggested not in structs:
                fields = [
                    (solidityType(s, n[0].upper() + n[1:]), n)
                    for n, s in schema["properties"].items()
                ]
                structs[suggested] = fields
            return suggested
        return schemaAbiField("value", schema, definitions)["type"]

    def declaration(schema, name, location):
        kind = solidityType(schema, name[0].upper() + name[1:])
        qualified = "P." + kind if kind in structs else kind
        suffix = " " + location if kind in structs or kind in {"bytes", "string"} else ""
        return f"{qualified}{suffix} {name}"

    commands = []
    for variant in definitions["Command"]["oneOf"]:
        props = variant["properties"]
        name = props["command"]["const"]
        args = ", ".join(
            declaration(s, n, "calldata") for n, s in props["input"]["properties"].items()
        )
        creation = name in {"createTask", "createChildTask"}
        output = " payable returns (P.TaskRef memory taskRef)" if creation else ""
        commands.append(f"    function {name}({args}) external{output};")
    events = []
    for variant in definitions["Event"]["oneOf"]:
        props = variant["properties"]
        name = props["name"]["const"]
        eventSchema = {
            "type": "object",
            "properties": {
                "schemaVersion": props["schemaVersion"],
                "policyVersion": props["policyVersion"],
                **props["payload"]["properties"],
            },
        }
        solidityType(eventSchema, name + "Data")
        events.append(f"    event {name}(P.{name}Data data);")

    def ref(name):
        return {"$ref": "#/$defs/" + name}

    def optional(name):
        return {"anyOf": [ref(name), {"type": "null"}]}

    fields = {
        "task": ref("TaskSpec"),
        "status": {"enum": list(catalog["states"])},
        "allocation": optional("Allocation"),
        "winningBid": optional("Bid"),
        "ownWorkReserveAtoms": ref("Uint96"),
        "childrenCreated": {"type": "integer"},
        "activeChildren": {"type": "integer"},
        "reservedChildBudgets": ref("Uint96"),
        "committedChildPayouts": ref("Uint96"),
        "result": optional("ResultCommitment"),
        "receipt": optional("SettlementReceipt"),
    }
    definitions["TaskView"] = {"type": "object", "properties": fields}
    viewSpecs = [
        ("readTask", {"taskRef": ref("TaskRef")}, {"view_": ref("TaskView")}),
        (
            "readBid",
            {"taskRef": ref("TaskRef"), "agentRef": ref("AgentRef")},
            {"bid": optional("Bid")},
        ),
        ("readSettlement", {"taskRef": ref("TaskRef")}, {"receipt": optional("SettlementReceipt")}),
        (
            "readCounters",
            {
                "agentRef": ref("AgentRef"),
                "taskFamily": {"type": "string"},
                "snapshotBlock": ref("Uint64"),
            },
            {"successes": ref("Uint64"), "failures": ref("Uint64")},
        ),
        ("readCredit", {"owner": ref("Address")}, {"amountAtoms": ref("Uint256")}),
        (
            "isNonceUsed",
            {"signer": ref("Address"), "primaryTypeHash": ref("Digest"), "nonce": ref("Uint256")},
            {"used": {"type": "bool"}},
        ),
        (
            "readPolicy",
            {},
            {
                "chainId": ref("Uint256"),
                "market": ref("Address"),
                "identityRegistry": ref("Address"),
                "validator": ref("Address"),
                "policyVersion": {"const": 1},
            },
        ),
        (
            "readAccounting",
            {},
            {
                "taskCount": ref("Uint64"),
                "depositedAtoms": ref("Uint256"),
                "escrowTotalAtoms": ref("Uint256"),
                "creditTotalAtoms": ref("Uint256"),
                "withdrawnAtoms": ref("Uint256"),
            },
        ),
    ]
    views, viewAbi = [], []
    for name, inputs, outputs in viewSpecs:
        args = ", ".join(declaration(s, n, "calldata") for n, s in inputs.items())
        returns = ", ".join(declaration(s, n, "memory") for n, s in outputs.items())
        views.append(f"    function {name}({args}) external view returns ({returns});")
        viewAbi.append(
            {
                "type": "function",
                "name": name,
                "stateMutability": "view",
                "inputs": [schemaAbiField(n, s, definitions) for n, s in inputs.items()],
                "outputs": [schemaAbiField(n, s, definitions) for n, s in outputs.items()],
            }
        )
    constants = []
    for category, prefix in [
        ("states", "STATE_"),
        ("terminalReasons", "REASON_"),
        ("verdicts", "VERDICT_"),
        ("counterEffects", "EFFECT_"),
        ("errors", ""),
        ("allocationOutcomes", "OUTCOME_"),
    ]:
        for name, value in catalog[category].items():
            constants.append(
                f"    uint{'16' if category == 'errors' else '8'} "
                f"internal constant {prefix}{name} = {value};"
            )
    records = [
        "    struct "
        + name
        + " {\n"
        + "\n".join(f"        {kind} {field};" for kind, field in fields)
        + "\n    }"
        for name, fields in structs.items()
    ]
    imports = 'import {ProtocolTypes as P} from "./ProtocolTypes.sol";\n\n'
    return {
        "contracts/src/ProtocolTypes.sol": HEADER
        + "library ProtocolTypes {\n"
        + "\n".join(constants)
        + "\n\n"
        + "\n\n".join(records)
        + "\n}\n",
        "contracts/src/IAgentLanceMarket.sol": HEADER
        + imports
        + "interface IAgentLanceMarket {\n    error ProtocolError(uint16 code);\n\n"
        + "\n".join(events)
        + "\n\n"
        + "\n".join(commands)
        + "\n}\n",
        "contracts/src/IAgentLanceViews.sol": HEADER
        + imports
        + "interface IAgentLanceViews {\n"
        + "\n".join(views)
        + "\n}\n",
        "specs/contracts.read.abi.json": json.dumps(viewAbi, indent=2) + "\n",
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in generate().items():
        if name.endswith(".sol"):
            from layer3_tools import toolPath

            content = subprocess.run(
                [toolPath("forge"), "fmt", "--raw", "-"],
                input=content,
                text=True,
                capture_output=True,
                check=True,
                cwd=ROOT,
            ).stdout
        path = ROOT / name
        if args.check:
            if not path.is_file() or path.read_text() != content:
                raise SystemExit(f"Generated file drift: {name}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == "__main__":
    main()
