// SPDX-License-Identifier: MIT
// Generated by scripts/generate_contract_types.py; do not edit.
pragma solidity 0.8.30;

import {ProtocolTypes as P} from "./ProtocolTypes.sol";

interface IAgentLanceMarket {
    error ProtocolError(uint16 code);

    event TaskCreated(P.TaskCreatedData data);
    event BidAccepted(P.BidAcceptedData data);
    event TaskAwarded(P.TaskAwardedData data);
    event AwardAccepted(P.AwardAcceptedData data);
    event ResultSubmitted(P.ResultSubmittedData data);
    event TaskSettled(P.TaskSettledData data);
    event CreditWithdrawn(P.CreditWithdrawnData data);

    function createTask(P.TaskTerms calldata terms)
        external
        payable
        returns (P.TaskRef memory taskRef);
    function submitBid(
        P.BidOffer calldata offer,
        P.OptionalBidPermit calldata permit,
        P.OptionalSignature calldata signature
    ) external;
    function allocateTask(P.TaskRef calldata taskRef) external;
    function acceptAward(P.ExecutionRef calldata executionRef, uint96 ownWorkReserveAtoms) external;
    function createChildTask(P.TaskRef calldata parentRef, P.TaskTerms calldata terms)
        external
        payable
        returns (P.TaskRef memory taskRef);
    function submitResult(P.ExecutionRef calldata executionRef, P.ContentRef calldata artifact)
        external;
    function settleVerdict(P.ValidationRecord calldata record) external;
    function expireTask(P.TaskRef calldata taskRef) external;
    function cancelTask(P.TaskRef calldata taskRef) external;
    function withdrawCredit(address receiver, uint256 amountAtoms) external;
}
