// SPDX-License-Identifier: MIT
// Generated by scripts/generate_contract_types.py; do not edit.
pragma solidity 0.8.30;

import {ProtocolTypes as P} from "./ProtocolTypes.sol";

interface IAgentLanceViews {
    function readTask(P.TaskRef calldata taskRef) external view returns (P.TaskView memory view_);
    function readBid(P.TaskRef calldata taskRef, P.AgentRef calldata agentRef)
        external
        view
        returns (P.OptionalBid memory bid);
    function readSettlement(P.TaskRef calldata taskRef)
        external
        view
        returns (P.OptionalSettlementReceipt memory receipt);
    function readCounters(
        P.AgentRef calldata agentRef,
        string calldata taskFamily,
        uint64 snapshotBlock
    ) external view returns (uint64 successes, uint64 failures);
    function readCredit(address owner) external view returns (uint256 amountAtoms);
    function isNonceUsed(address signer, bytes32 primaryTypeHash, uint256 nonce)
        external
        view
        returns (bool used);
    function readPolicy()
        external
        view
        returns (
            uint256 chainId,
            address market,
            address identityRegistry,
            address validator,
            uint8 policyVersion
        );
    function readAccounting()
        external
        view
        returns (
            uint64 taskCount,
            uint256 depositedAtoms,
            uint256 escrowTotalAtoms,
            uint256 creditTotalAtoms,
            uint256 withdrawnAtoms
        );
}
