// SPDX-License-Identifier: MIT
// Generated by scripts/generate_contract_types.py; do not edit.
pragma solidity 0.8.30;

library ProtocolTypes {
    uint8 internal constant STATE_OPEN = 0;
    uint8 internal constant STATE_AWARDED = 1;
    uint8 internal constant STATE_RUNNING = 2;
    uint8 internal constant STATE_SUBMITTED = 3;
    uint8 internal constant STATE_SETTLED = 4;
    uint8 internal constant REASON_SUCCESS = 1;
    uint8 internal constant REASON_VALIDATION_FAILED = 2;
    uint8 internal constant REASON_NO_SHOW = 3;
    uint8 internal constant REASON_EXECUTION_TIMEOUT = 4;
    uint8 internal constant REASON_VALIDATOR_TIMEOUT = 5;
    uint8 internal constant REASON_UNALLOCATED = 6;
    uint8 internal constant REASON_ALLOCATION_EXPIRED = 7;
    uint8 internal constant REASON_CANCELLED = 8;
    uint8 internal constant VERDICT_FAIL = 0;
    uint8 internal constant VERDICT_PASS = 1;
    uint8 internal constant EFFECT_NONE = 0;
    uint8 internal constant EFFECT_SUCCESS = 1;
    uint8 internal constant EFFECT_FAILURE = 2;
    uint16 internal constant INVALID_ENCODING = 1;
    uint16 internal constant INVALID_RANGE = 2;
    uint16 internal constant UNKNOWN_TASK = 3;
    uint16 internal constant ALREADY_SETTLED = 4;
    uint16 internal constant WRONG_STATE = 5;
    uint16 internal constant UNAUTHORIZED = 6;
    uint16 internal constant INVALID_TERMS = 7;
    uint16 internal constant UNSUPPORTED_POLICY = 8;
    uint16 internal constant INVALID_ASSET = 9;
    uint16 internal constant INVALID_BUDGET = 10;
    uint16 internal constant INVALID_ALPHA = 11;
    uint16 internal constant INVALID_DEADLINES = 12;
    uint16 internal constant WRONG_VALUE = 13;
    uint16 internal constant IDENTITY_UNAVAILABLE = 14;
    uint16 internal constant OWNER_CHANGED = 15;
    uint16 internal constant WALLET_UNSET = 16;
    uint16 internal constant WALLET_MISMATCH = 17;
    uint16 internal constant VALIDATOR_CONFLICT = 18;
    uint16 internal constant INVALID_SIGNATURE = 19;
    uint16 internal constant NONCE_USED = 20;
    uint16 internal constant SIGNATURE_EXPIRED = 21;
    uint16 internal constant DUPLICATE_AGENT = 22;
    uint16 internal constant BID_OVER_BUDGET = 23;
    uint16 internal constant TOO_EARLY = 24;
    uint16 internal constant DEADLINE_PASSED = 25;
    uint16 internal constant INVALID_RESERVE = 26;
    uint16 internal constant INVALID_PARENT = 27;
    uint16 internal constant DEPTH_LIMIT = 28;
    uint16 internal constant CHILD_LIMIT = 29;
    uint16 internal constant ENVELOPE_EXCEEDED = 30;
    uint16 internal constant CHILD_DEADLINE = 31;
    uint16 internal constant INVALID_RETRY = 32;
    uint16 internal constant CHILDREN_ACTIVE = 33;
    uint16 internal constant RESULT_MISMATCH = 34;
    uint16 internal constant POLICY_MISMATCH = 35;
    uint16 internal constant INSUFFICIENT_CREDIT = 36;
    uint16 internal constant TRANSFER_FAILED = 37;
    uint16 internal constant REENTRANCY = 38;
    uint16 internal constant TASK_LIMIT = 39;
    uint8 internal constant OUTCOME_AWARDED = 0;
    uint8 internal constant OUTCOME_UNALLOCATED = 1;

    struct Asset {
        string kind;
        string symbol;
        uint8 decimals;
    }

    struct ContentRef {
        string uri;
        bytes32 digest;
    }

    struct DelegationLimits {
        uint32 maxDepth;
        uint32 maxChildren;
    }

    struct TaskRef {
        uint256 chainId;
        address market;
        uint64 taskId;
    }

    struct OptionalTaskRef {
        bool present;
        TaskRef value;
    }

    struct TaskTerms {
        uint8 policyVersion;
        address refundAddress;
        Asset asset;
        uint96 budgetAtoms;
        ContentRef input;
        ContentRef outputSchema;
        string taskFamily;
        uint96 alphaNum;
        uint96 alphaDen;
        uint64 biddingClose;
        uint64 allocationBy;
        uint64 acceptBy;
        uint64 resultBy;
        uint64 validationBy;
        address validator;
        ContentRef validationPolicy;
        DelegationLimits delegation;
        OptionalTaskRef retryOf;
    }

    struct AgentRef {
        uint256 chainId;
        address identityRegistry;
        uint256 agentId;
    }

    struct BidOffer {
        TaskRef taskRef;
        AgentRef agentRef;
        uint96 bidAtoms;
        address executionSigner;
        address payout;
        bytes32 profileDigest;
    }

    struct BidPermit {
        TaskRef taskRef;
        AgentRef agentRef;
        address owner;
        address executionSigner;
        address payout;
        uint96 bidAtoms;
        bytes32 profileDigest;
        uint256 nonce;
        uint64 expiry;
    }

    struct OptionalBidPermit {
        bool present;
        BidPermit value;
    }

    struct OptionalSignature {
        bool present;
        bytes value;
    }

    struct ExecutionRef {
        TaskRef taskRef;
        uint8 awardId;
    }

    struct ValidationRecord {
        uint8 schemaVersion;
        ExecutionRef executionRef;
        AgentRef agentRef;
        bytes32 resultDigest;
        bytes32 validationPolicyDigest;
        uint8 verdict;
        ContentRef evidence;
        address validator;
        uint256 nonce;
        uint64 expiry;
        bytes signature;
    }

    struct TaskSpec {
        uint8 schemaVersion;
        TaskRef taskRef;
        address requester;
        TaskTerms terms;
        OptionalTaskRef parentRef;
        TaskRef rootRef;
        uint32 depth;
        uint64 createdAt;
        uint64 createdBlock;
        uint64 reputationSnapshotBlock;
    }

    struct TaskCreatedData {
        uint8 schemaVersion;
        uint8 policyVersion;
        TaskSpec task;
    }

    struct Counters {
        uint64 successes;
        uint64 failures;
    }

    struct Bid {
        uint8 schemaVersion;
        BidOffer offer;
        address ownerAtBid;
        uint64 snapshotBlock;
        Counters counters;
        uint32 p;
        int256 score;
    }

    struct OptionalUint256 {
        bool present;
        uint256 value;
    }

    struct BidAcceptedData {
        uint8 schemaVersion;
        uint8 policyVersion;
        Bid bid;
        OptionalUint256 permitNonce;
    }

    struct OptionalAgentRef {
        bool present;
        AgentRef value;
    }

    struct OptionalInt256 {
        bool present;
        int256 value;
    }

    struct OptionalUint96 {
        bool present;
        uint96 value;
    }

    struct Allocation {
        uint8 schemaVersion;
        TaskRef taskRef;
        uint8 mechanismVersion;
        uint8 outcome;
        OptionalAgentRef winner;
        uint32 awardId;
        OptionalInt256 winningScore;
        OptionalInt256 secondScore;
        OptionalUint96 criticalAtoms;
        uint96 reservedAtoms;
        uint64 allocatedAt;
    }

    struct TaskAwardedData {
        uint8 schemaVersion;
        uint8 policyVersion;
        Allocation allocation;
    }

    struct AwardAcceptedData {
        uint8 schemaVersion;
        uint8 policyVersion;
        ExecutionRef executionRef;
        uint96 ownWorkReserveAtoms;
        uint64 acceptedAt;
    }

    struct ResultCommitment {
        uint8 schemaVersion;
        ExecutionRef executionRef;
        ContentRef artifact;
        uint64 submittedAt;
    }

    struct ResultSubmittedData {
        uint8 schemaVersion;
        uint8 policyVersion;
        ResultCommitment result;
    }

    struct OptionalAddress {
        bool present;
        address value;
    }

    struct OptionalDigest {
        bool present;
        bytes32 value;
    }

    struct OptionalValidationRecord {
        bool present;
        ValidationRecord value;
    }

    struct SettlementReceipt {
        uint8 schemaVersion;
        TaskRef taskRef;
        uint8 reason;
        OptionalAgentRef winner;
        OptionalAddress payout;
        address refundAddress;
        uint96 budgetAtoms;
        uint96 reservedAtoms;
        uint96 paidAtoms;
        uint96 refundAtoms;
        OptionalDigest resultDigest;
        OptionalValidationRecord validation;
        uint8 counterEffect;
        uint64 settledAt;
    }

    struct TaskSettledData {
        uint8 schemaVersion;
        uint8 policyVersion;
        SettlementReceipt receipt;
    }

    struct CreditWithdrawnData {
        uint8 schemaVersion;
        uint8 policyVersion;
        address owner;
        address receiver;
        uint256 amountAtoms;
    }

    struct OptionalAllocation {
        bool present;
        Allocation value;
    }

    struct OptionalBid {
        bool present;
        Bid value;
    }

    struct OptionalResultCommitment {
        bool present;
        ResultCommitment value;
    }

    struct OptionalSettlementReceipt {
        bool present;
        SettlementReceipt value;
    }

    struct TaskView {
        TaskSpec task;
        uint8 status;
        OptionalAllocation allocation;
        OptionalBid winningBid;
        uint96 ownWorkReserveAtoms;
        uint32 childrenCreated;
        uint32 activeChildren;
        uint96 reservedChildBudgets;
        uint96 committedChildPayouts;
        OptionalResultCommitment result;
        OptionalSettlementReceipt receipt;
    }
}
